# Generated by Django 5.0.1 on 2024-02-03 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='product',
            name='createat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default='7', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='7', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updateat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
