# Generated by Django 5.0.1 on 2024-02-03 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(max_length=200, null=True)),
                ('createat', models.DateTimeField(default=datetime.datetime(2024, 2, 3, 20, 58, 25, 850195, tzinfo=datetime.timezone.utc), null=True)),
                ('updateat', models.DateTimeField(default=datetime.datetime(2024, 2, 3, 20, 58, 25, 850195, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
